name: Release package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # nodig om release assets te uploaden

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve version from tag
        id: v
        run: |
          TAG="${GITHUB_REF_NAME}"            # e.g. v0.3.6
          NAME="Plex-SIMKL-Watchlist-Sync ${TAG}.zip"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "zipname=${NAME}" >> $GITHUB_OUTPUT

      - name: Create release ZIP
        run: |
          mkdir -p dist
          zip -9 -j "dist/${{ steps.v.outputs.zipname }}" \
            config.example.json \
            plex_simkl_watchlist_sync.py \
            README.md

      - name: Publish GitHub Release (create or update)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.v.outputs.tag }}
          files: |
            dist/${{ steps.v.outputs.zipname }}
          generate_release_notes: true
